import './globals.css'
import { Inter } from 'next/font/google'
// global messages
import { MessageProvider } from './context/MessageContext'
import MessageBanner from './components/MessageBanner'

// tell next to render dynamic and not static pages at build time
export const dynamic = 'force-dynamic'

const inter = Inter({ subsets: ['latin'] })

// components
import Sidebar from './components/Sidebar'
import Footer from './components/Footer'

// metadata
export const metadata = {
  title: 'My Portfolio',
  description: 'A portfolio showcasing my work generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col xl:flex-row">
          <Sidebar />
          <div className="main-container flex-1 uw:relative uw:right-[200px]">
            <MessageProvider>
              <MessageBanner />
              {children}
            </MessageProvider>
          </div>
        </div>
        <Footer />
      </body>
    </html>
  )
}
