import './globals.css'
import { Inter } from 'next/font/google'

// tell next to render dynamic and not static pages at build time
export const dynamic = 'force-dynamic'

// global messages
import { MessageProvider } from './context/MessageContext'
import MessageBanner from './components/MessageBanner'

const inter = Inter({ subsets: ['latin'] })

// components
import Sidebar from './components/Sidebar'

// metadata
export const metadata = {
  title: 'My Portfolio',
  description: 'A portfolio showcasing my work generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <div className="flex flex-col">
            <Sidebar />
            <div>
              <MessageProvider>
                <MessageBanner />
                {children}
              </MessageProvider>
            </div>
          </div>
      </body>
    </html>
  )
}
