import './globals.css'
import { Inter } from 'next/font/google'
// global messages
import { MessageProvider } from './context/MessageContext'
import MessageBanner from './components/MessageBanner'

// tell next to render dynamic and not static pages at build time
export const dynamic = 'force-dynamic'

const inter = Inter({ subsets: ['latin'] })

// components
import Footer from './components/Footer'

// metadata
export const metadata = {
  title: 'My Portfolio',
  description: 'A portfolio showcasing my work generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="main-container">
          <MessageProvider>
            <MessageBanner />
            {children}
          </MessageProvider>
        </div>
        <Footer />
      </body>
    </html>
  )
}
